package edu.uky.cs.nil.sg;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.PriorityQueue;
import java.util.function.BiFunction;
import java.util.function.Function;

import edu.uky.cs.nil.sg.ExpandedNode.EdgeStub;
import edu.uky.cs.nil.tt.Role;
import edu.uky.cs.nil.tt.world.Constant;
import edu.uky.cs.nil.tt.world.Entity;
import edu.uky.cs.nil.tt.world.LogicalWorld;
import edu.uky.cs.nil.tt.world.State;
import edu.uky.cs.nil.tt.world.Value;
import edu.uky.cs.nil.tt.world.Variable;

/**
 * A graph expander manages the generation of a {@link StoryGraph story graph}
 * from a {@link LogicalWorld Tandem Tales logical story world}, serving as a
 * central point for many node expanding threads to report their work and
 * ensuring that nodes are generated in a deterministic order.
 * <p>
 * This process can be given a {@link #max maximum depth} to expand the graph.
 * A max depth of 1 means it will generate all states which can be reached by
 * taking up to 1 action from the initial state. A max depth of 2 means it will
 * generate all states which can be reached by taking up to 2 actions from the
 * initial state, and so on. The last layer of nodes generated by this method
 * will still have outgoing {@link TemporalEdge temporal edges}, but only if
 * they lead to nodes generated earlier in the process (i.e. nodes at a lower
 * depth). In other words, if this process runs with a max depth of 5, it means
 * the graph will include any state which can be reached by a sequence of up to
 * 5 actions from the initial state, and from those nodes it is still possible
 * to move to other states to, but only if those states were also generated at
 * depth 5 or lower.
 * <p>
 * If this process runs without a max depth, it will run until all reachable
 * states have been generated. Assuming the graph is finite, it will eventually
 * halt.
 * <p>
 * This object's synchronized methods ensure that, while many threads might be
 * running simultaneously to expand nodes, only one thread at a time is
 * modifying the story graph. This object also ensures that nodes are expanded
 * in order of {@link Node#getID() their IDs}, meaning this procedure will
 * always produce the same story graph despite the non-determinism introduced
 * by concurrency.
 * <p>
 * While many threads can be working to expand nodes at once, because they must
 * all coordinate with this object to add new nodes to the graph, the speedup
 * from running many threads is minimal.
 * 
 * @author Stephen G. Ware
 */
public class GraphExpander implements Task {
	
	/** The Tandem Tales story world for which the graph is being generated */
	public final LogicalWorld world;
	
	/** A function that maps character utilities to states */
	public final BiFunction<String, State, Double> utility;
	
	/**
	 * The story graph this generator is creating. This story graph should not
	 * be accessed or modified by other threads while the generation process is
	 * running.
	 */
	public final StoryGraph graph;
	
	/**
	 * The maximum depth that breadth-first search should go when generating the
	 * story graph, where depth 1 means all states which can be reached via one
	 * action from the initial state, depth 2 means all states which can be
	 * reached via two actions from the initial state, etc.
	 */
	public final int max;
	
	/** The number of node-expanding threads to run simultaneously */
	private final NodeExpander[] threads;
	
	/** Maps Tandem Tales states to their equivalent story graph nodes */
	private final BigMap<State, Node> nodes = new BigHashMap<>();
	
	/** A queue of new Tandem Tales states waiting to be expanded */
	private final BigBlockingQueue<ExpandedNode> queue = new BigBlockingQueue<>();
	
	/**
	 * A priority queue of nodes which have been expanded but not yet added to
	 * the story graph
	 */
	private final PriorityQueue<ExpandedNode> complete = new PriorityQueue<>();
	
	/** The status object that will be updated each time a node is expanded */
	private Status status;
	
	/** The current depth of the search */
	private int depth = 0;
	
	/** The ID of the next story graph node that needs to be completed */
	private long next = 0;
	
	/** The total number of nodes at the previous search depth */
	private long previous = 0;
	
	/**
	 * The time this depth of the search started in milliseconds since the Epoch
	 */
	private long started;
	
	/**
	 * Creates a new Tandem Tales story graph expander.
	 * 
	 * @param world the Tandem Tales story world that defines the graph
	 * @param utility a mapping of character utilities to states
	 * @param graph the story graph generated
	 * @param max the maximum depth to which the generation process should go
	 * @param threads the number of simultaneous node-expanding threads that
	 * should run simultaneously to generate the graph
	 */
	public GraphExpander(LogicalWorld world, BiFunction<String, State, Double> utility, StoryGraph graph, int max, int threads) {
		this.world = world;
		this.utility = utility;
		this.graph = graph;
		this.max = max;
		this.threads = new NodeExpander[Math.max(threads, 1)];
		for(int i = 0; i < this.threads.length; i++)
			this.threads[i] = new NodeExpander(this);
	}
	
	@Override
	public void run(Status status) throws Exception {
		this.status = status;
		status.set("Expanding depth 0", 1L);
		started = System.currentTimeMillis();
		// Create root node.
		get(world.start(Role.GAME_MASTER).getState());
		// Run node expander threads.
		for(NodeExpander thread : threads)
			thread.start();
		for(NodeExpander thread : threads)
			thread.join();
	}
	
	/**
	 * Returns the story graph node associated with the given Tandem Tales
	 * state. If no such node exists, it will be created (unless doing so
	 * would violate the {@link #max max depth} constraint).
	 * 
	 * @param state a Tandem Tales state
	 * @return the equivalent story graph node
	 */
	private synchronized Node get(State state) {
		Node node = nodes.get(state);
		// Only create a node if there is no max depth or if the node is at or
		// before the max depth.
		if(node == null && (max <= 0 || depth < max)) {
			Function<Fluent, Object> values = fluent -> {
				Variable variable = world.getVariable(fluent.getID());
				Value value = state.get(variable);
				if(value == Constant.NULL)
					return null;
				else if(value instanceof Entity)
					return value.toString();
				else
					return value.toNumber();
			};
			Function<Character, Double> utility = character -> {
				String name = character == null ? null : character.name;
				return this.utility.apply(name, state);
			};
			node = graph.nodes.add(values, utility);
			nodes.put(state, node);
			// Adding the node to blocking queue wakes up one thread which is
			// waiting for a node to expand.
			queue.push(new ExpandedNode(state, node));
		}
		return node;
	}
	
	/**
	 * Returns the next state node to expand, blocking until one becomes
	 * available, or returning null if the wait is interrupted.
	 * 
	 * @return the next state node that needs to be expanded
	 */
	ExpandedNode pop() {
		try {
			return queue.pop();
		}
		catch(InterruptedException exception) {
			return null;
		}
	}
	
	/**
	 * Notifies this object that a node has been expanded and its edges should
	 * now be added to the story graph.
	 * 
	 * @param node the node whose edges have been expanded
	 */
	synchronized void push(ExpandedNode node) {
		// Ensure nodes are completed in order by adding them to a priority queue...
		complete.offer(node);
		// ... and only popping off the next node to be added.
		while(!complete.isEmpty() && complete.peek().tail.getID() == next) {
			// Add all edges for this node.
			ExpandedNode expanded = complete.poll();
			for(EdgeStub stub : expanded.edges) {
				Action label = graph.actions.get(stub.action.getID());
				Node head = get(stub.after);
				if(head != null)
					graph.edges.temporal.add(expanded.tail, label, head);
			}
			// Increment counters.
			status.increment();
			next++;
			// Check if it is time to move to the next search depth.
			if(status.getCount() == status.getTotal()) {
				// Print statistics for this depth.
				String message = "\rDepth " + depth + ": " + status.getTotal() + " nodes, ";
				message += edu.uky.cs.nil.sabre.Utilities.time(System.currentTimeMillis() - started) + " ";
				if(previous > 0) {
					BigDecimal abf = new BigDecimal(status.getTotal()).divide(new BigDecimal(previous), 2, RoundingMode.HALF_UP);
					message += "(" + abf + " average branching factor) ";
				}
				System.out.println(message);
				// If expansion is complete, stop all expander threads.
				if(graph.nodes.size() == next) {
					for(NodeExpander thread : threads)
						thread.interrupt();
				}
				// Otherwise, move to the next depth.
				else {
					depth++;
					previous = status.getTotal();
					started = System.currentTimeMillis();
					if(depth < max)
						status.setMessage("Expanding depth " + depth);
					else
						status.setMessage("Processing depth " + depth);
					status.setTotal(graph.nodes.size() - next);
				}
			}
		}
	}
}